### ISSUE TITLE
Ideias iniciais do projeto!

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/gdg.ninjas#1]
O gdg.ninjas é um projeto para substituir o atual site do GDG Aracaju, mas com muito mais funcionalidades. Comente com suas idéias!

**Comment by erickmendonca** [comment]
Seria massa usar a API do GitHub pra controlar membros :) A aplicação seria toda construída com AngularJS.

**Comment by erickmendonca** [comment]
Básico:
- lista de eventos
- lista de membros
- lista de grupos/redes sociais/tudo do gdg aracaju
- botão para inscrever-se

**Comment by erickmendonca** [comment]
Ideias que a galera mandou no **grupo do Telegram**:
- Perfil dos membros com contatos e agregador de publicações.
- Projetos

**Comment by fernandomalmeida** [comment]
Grupo do Instagram? kkkkkkkkkkkkkkkk

Enfim, não entendi como seria a api do github para controlar os membros.
Seriam os contribuidores da organização GDG Aracaju?

Em 19 de outubro de 2015 13:29, Erick Mendonça notifications@github.com
escreveu:

**Comment by erickmendonca** [comment]
@fernandomalmeida eu tinha corrigido, mas no email já era haha :+1: 

Sim, os membros ficariam num time aqui na organização do GDG Aracaju no GitHub :) E os palestrantes em outro, etc.

**Comment by raphaelpanta** [comment]
A parte das tecnologias, no seria angularjs no front end. 
Haveria necessidade de backend? 
Na parte de membros, o github tem alguma API para expor as contribuições de cada membro e o perfil de cada um?

**Comment by eduardoborges** [comment]
Seria bom fazer um escopo de como vai ficar isso. Tanto a estrutura e dados da homepage quanto ao sistema que vai rodar. Ai fica mais easy pro pessoal colaborar.

**Comment by erickmendonca** [comment]
Sim, esse tópico aqui é pra delimitar o escopo :+1:

**Comment by erickmendonca** [comment]
@raphaelpanta talvez não precise de backend, se conseguirmos colocar tudo pela API do GitHub!

Sobre guardar as contribuições de cada membro, podemos tentar com um repositório que guarde essas coisas ou então realmente criar um backend para algumas coisas pontuais, como essa.

**Comment by fernandomalmeida** [comment]
Acho interessante colocar um nível de prioridade para saber o que fazer primeiro e o que fazer em seguida.
1. lista de eventos
2. lista de grupos/redes sociais/tudo do gdg aracaju
3. lista de membros
4. botão para inscrever-se
5. Perfil dos membros com contatos e agregador de publicações.
6. Projetos

Assim já sabemos como atacar no começo.
Para facilitar o backend, poderíamos colocar informações gravadas em json mesmo (como a parte da lista de grupos/redes sociais/tudo), outras consumindo serviços (Lista de Eventos -> Google Calendar, Lista de membros -> Github etc). Assim daria para hospedar até no githubpages

**Comment by erickmendonca** [comment]
Estamos catalogando as ideias e vocês já querem priorizar! :smile: 

@fernandomalmeida acho que é isso mesmo, massa :) Só acho que esses json devem ficar em um outro repositório, para não misturar com código. Assim a gente pode até abrir o código pra outros gdgs utilizarem.

Uma ideia que acho bacana também é listar todas as formas de contato do GDG logo na inscrição. Participar delas poderiam valer pontos e a gente pode incluir outras coisas para gamificar o GDG e incluir algumas recompensas :heart:

**Comment by erickmendonca** [comment]
![teenagemutantninjaandroids](https://cloud.githubusercontent.com/assets/1076654/10588814/722eb8de-767e-11e5-9714-9bc9626dcc93.jpg)

**Comment by diegomelo182** [comment]
Posso ajudar no AngularJS @erickmendonca e layout! ah e podemos usar o Material Design Lite do Google já que seria para o site do GDG já dava uma força usando esse framework frontend do Google o que acham? @fernandomalmeida @eduardoborges @raphaelpanta

**Comment by diegomelo182** [comment]
Os templates seriam esses aqui: http://www.getmdl.io/templates/android-dot-com/index.html e  http://www.getmdl.io/templates/text-only/index.html @erickmendonca @fernandomalmeida @eduardoborges @raphaelpanta

**Comment by erickmendonca** [comment]
@diegomelo182 Por mim pode ser o mdl! Colocando umas classes mais legiveis fica show :)

**Comment by raphaelpanta** [comment]
@diegomelo182  gostei dos templates!
@erickmendonca como ficaria essa questão dos repositórios, quem quiser ter seus dados, mandaria um pull request com seu json? 

@erickmendonca @fernandomalmeida como seria essa parte de gamificação?

Posso contribuir com o AngularJS!

Vocês achariam interessante também ter link para quem quiser doar para manutenção do site, infra, no caso de ter algo mais complexo(e claro contar como pontuação)?

**Comment by erickmendonca** [comment]
@raphaelpanta 
- repositório de JSON: sim, podem rolar pull requests ou edição direta pelos organizadores
- gamificação: poderíamos fazer uma pontuação por assiduidade e/ou outras formas, colocar níveis e até premiações com parceiros!
- doações para infra: caso seja necessário, com certeza :)

**Comment by randhson** [comment]
Seria interessante tbm, colocar os parceiros do GDG para eventos. Como o barcode, code dojo-se, e o rockincode !

**Comment by erickmendonca** [comment]
@randhson boa!

**Comment by gabrielaraujof** [comment]
@erickmendonca já que a idéia é catalogar idéias (para posteriormente priorizá-las) seria uma boa criar uma board aberta no [Trello](https://trello.com/), não? Ou em algum serviço free (e simples) de gerencimento de projetos.

**Comment by diegomelo182** [comment]
@gabrielaraujof boa idéia cara, o Trello é bacana se a não cair no gosto da galera  tem o [Asana](https://app.asana.com/) e o [Azendoo](https://www.azendoo.com/) para fazer o gerenciamento desse projeto.

**Comment by erickmendonca** [comment]
@gabrielaraujof @diegomelo182 Acho muito bacana a ideia do Trello, mas acho que a board aberta pode bagunçar. Mas a gente pode organizar lá sim! Quem tá a fim de criar isso lá?

**Comment by gabrielaraujof** [comment]
@erickmendonca Criado! [https://trello.com/gdgaracaju](https://trello.com/gdgaracaju)
Tanto o time, quanto a board está pública (qualquer um pode ver), mas edição somente quem for convidado!

A parte ruim é que não achei um link pra convites... Então teria que convidar manualmente pelo email ou `username` da galera.

Se a galera aceitar lá mesmo, é só passar os usernames/emails pra adicionar lá.

**Comment by erickmendonca** [comment]
Meu user: erickmendonca

**Comment by fernandomalmeida** [comment]
Meu user: fernandose

2015-10-21 14:10 GMT-03:00 Erick Mendonça notifications@github.com:

**Comment by raphaelpanta** [comment]
username: raphaelpanta

**Comment by diegomelo182** [comment]
username: diegomelo7

**Comment by erickmendonca** [comment]
@diegomelo182 Voltando a falar do front, nós podemos criar classes que herdam daquelas do CSS do MDL né? Seria ótimo criar algumas pra servir de referência para quem fosse implementando sem ter de fuçar tanto nas stylesheets :+1:

**Comment by gabrielaraujof** [comment]
@erickmendonca @diegomelo182  Eu apoio! Seria uma mão-na-roda para quem estivesse focado na parte de funcionalidades, e principalmente, para manter o padrão de estilo (senão cada um aplica seu próprio estilo e ~~vira uma zona do caraleo~~ fica confuso).

**Comment by diegomelo182** [comment]
@gabrielaraujof @erickmendonca dá pra fazer as heranças com o sass de boas, posso ficar responsável pelo front end se quiserem e for usar mesmo o AngularJS posso dar uma mãozinha também.

**Comment by diegomelo182** [comment]
Abri uma issue para definirmos o layout do projeto

**Comment by erickmendonca** [comment]
Já catalogamos uma boa base pra começar. Na issue #2 vamos votar qual layout usaremos agora no começo e vamos botar pra funcionar!

[Lá no Trello vamos organizar as tarefas. Hora de encher o backlog!](http://trello.com/gdgaracaju)

**Comment by randhson** [comment]
@erickmendonca ou @gabrielaraujof me add la no trello como membro.

**Comment by eduardoborges** [comment]
meu user @borgeseduardo <3

2015-10-28 10:47 GMT-03:00 Randson Nunes notifications@github.com:

**Comment by randhson** [comment]
Como não consigo votar pelo trello, voto aqui mesmo.
"Material Design Lite - android.com MDL skin"

**Comment by erickmendonca** [comment]
@randhson qual seu email ou usuário no trello?

**Comment by randhson** [comment]
@randsonnunes

**Comment by erickmendonca** [comment]
Conjunto inicial de features fechado :)
