### ISSUE TITLE
Definir o template que vamos usar no projeto

### ISSUE THREAD

**Issue by diegomelo182** [GDGAracaju/gdg.ninjas#2]
Vamos fazer uma votação ou entrar em consenso para definir o layout do projeto

**Comment by erickmendonca** [comment]
@diegomelo182 Cola aqui umas screenshots e numera, assim a gente vota!

**Comment by diegomelo182** [comment]
OK @erickmendonca faço isso amanhã pela manhã

**Comment by raphaelpanta** [comment]
Gostei bastante do template Material Design Lite - Text-Heavy Webpage que vi no trello. Como está sendo a votação, aqui ou no trello?

**Comment by erickmendonca** [comment]
Pois é, pensei que seria aqui! Acho que o Text-Heavy fica bacana :shipit: :+1:

**Comment by erickmendonca** [comment]
votação encerrada! Agora vamos decidir qual implementação do material design usar: MDL vs Angular Material. Votem!

**Comment by randhson** [comment]
Já que o template vai ser o MDL - Text-Heavy, acho que o mais adequado é a implementação do MDL mesmo.

**Comment by erickmendonca** [comment]
MDL wins!  :shipit:
