### ISSUE TITLE
Chat para os colaboradores

### ISSUE THREAD

**Issue by raphaelpanta** [GDGAracaju/gdg.ninjas#3]
Seria bom formalizar um canal de comunicação para a gente, algo como hipchat, tirar dúvidas com quem tiver online, discutir ideias. 
Sinto que um canal de comunicação mais focado ajudaria muito, do que os canais atuais.
Algumas possibilidades:
- Hipchat
- Telegram 
- Whatsapp
- Skype

O hipchat eu acho ideal, possui integração com o github entre outras coisas.

**Comment by gabrielaraujof** [comment]
Concordo Raphael. Inclusive com a preferência pelo hip chat. Qualquer coisa tem o slack também.

**Comment by erickmendonca** [comment]
O slack já existe. Vou criar um canal lá então!

**Comment by erickmendonca** [comment]
Outra opção era usar o Gitter, dêem uma olhada :)

**Comment by erickmendonca** [comment]
No Slack: https://gdgbrazil.slack.com/messages/gdg_ninjas/

Quem não tem conta ainda, pede convite em: http://gdgbrazil.herokuapp.com/

**Comment by erickmendonca** [comment]
Slack here we go! :shipit:
